### PR TITLE
Allow periods in the input ng-model attribute

### PR DESCRIPTION
**Pull request by barefootdeveloper**
I created this modified version that doesn't replace the periods that may be present in the ng-model attribute of an input.   This is pretty critical for this section of code to work as expected with controller as syntax.

I did a brief test and didn't see anything negative happening as a result of this, but I'm certainly open to a dialog about it.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you for your PR.

Could you explain me a little bit more verbosely why this is required for the 'controller as'-syntax to work as expected, maybe give me an example or something? I'm not familiar with the part of angular which handles the name-attributes but they're definitely interpolated somewhere for the validation without ng-messages, and that's why they're being replaced. Could also be, that setting the name attribute is not needed anymore - it was originally implemented when ng-fab-form wasn't using ng-messages, but the old way of validations. But I would have to dig a little bit into that.

Also you don't need to bump the version number. The one in the bower and the package version isn't correct anyway (at least bower doesn't use them, so its not too important).

**Comment by barefootdeveloper** [comment]
It's not really required for controller as syntax to work necessarily but it certainly makes certain things easier.

Take the scenario where we have:
```html
<form name="ctrl.form">
   <label for="ctrl.field">A Fancy Label</label>
   <input type="text" id="ctrl.field" ng-model="ctrl.field"/>
</form>
```
This gets processed as
```html
<form name="ctrl.form">
    <label for="ctrl.field">A Fancy Label</label>
    <input type="text" id="ctrl.field" ng-model="ctrl.field" name="ctrl_field"/>
</form>
```
whenever you're iterating through ctrl.form.$error you have access to the input elements $name but not it's other properties [at least not as obviously, I'm by no means an expert].

It seems like it would be convenient for all of these references to line up.  For example I was planning to implement a validation summary that, among other sources, would look for labels associated with that input to make sure the validation error text matched what was displayed to the user.

We could of course just name the input fields identically if we wanted but it's really great how your tool will make sure all inputs have names.

Do you know why you originally replaced the periods to begin with?  I'm just curious I tried researching a reason for doing it and couldn't come up with anything

Thanks for the tip on the version number.  I was actually trying to figure out how to get bower to pull from my local repository and it took me a bit to realize I had to create a release in github for it to pull down.    Every day is a learning experience right :)

**Comment by johannesjo** [comment]
Ok. I will merge your PR, but you should provide it again without the bower.json commit.

It would also be no problem to add the change manually. Don't know if contributions are important to you, but I don't want to steal them from you :)

**Comment by barefootdeveloper** [comment]
Excellent thanks a lot :)   I pulled out the version number bump from my fork.

The contribution thing doesn't really bother me, but it's always nice :)

**Pull request merged**
