### PR TITLE
ngFabEnsureExpression with test cases added

### PR DESCRIPTION
**Pull request by tushariscoolster**
ngFabEnsureExpression with test cases added

### CODE REVIEW

**Comment by tushariscoolster** [comment]
Am sure, your default-validation-msgs.js dint gt changed,
test runned perfectly on my local,
i had to delete that file and again need to generate it by grunt.

**Comment by johannesjo** [comment]
You probably want to develop using the grunt tasks. I suppose the test fails, because the default validation-messages-file (https://github.com/johannesjo/ng-fab-form/blob/master/src/default-validation-msgs.js) is not created properly, which is used for tests and for the bower version.

There also two minor things: The formation of the default-validation-msgs.html shouldn't change and for further development it would be also very helpful to have more helpful commit messages :)

Yo can do the latter by doing a rebase, e.g.:
```
git rebase -i HEAD~3
```
Put something descriptive in it like `added ngFabEnsureExpression validation directive #58`

I would do that myself, but I'm not sure if you would still be listed under the contributors section then. 

Thank you very much again. I know that this might seam tiresome, but for future development it is vital to have tests and a useful git history.

**Comment by tushariscoolster** [comment]
Thanks for your suggession;
Should i go with by making new pull request now?

**Comment by johannesjo** [comment]
Yes please! :)

**Pull request closed without merging**
