### PR TITLE
added ngFabEnsureExpression validation directive

### PR DESCRIPTION
**Pull request by tushariscoolster**
Added new validation directive ngFabEnsureExpression which validate form based on condition

### CODE REVIEW

**Comment by johannesjo** [comment]
There is still the default-validation-messages.js missing.

**Comment by tushariscoolster** [comment]
Commited now

**Comment by tushariscoolster** [comment]
now?

**Comment by tushariscoolster** [comment]
I donno why it is failing now?

**Comment by johannesjo** [comment]
I'll check it out!

**Comment by tushariscoolster** [comment]
Kk

**Comment by johannesjo** [comment]
Actually there was in jshint issue with the spec (doublequotes instead of single ones) so the build failed and then the tests failed. Don't know why travis didn't throw an error about that though.

**Comment by tushariscoolster** [comment]
Aww got it...thanks for your efforts

**Comment by johannesjo** [comment]
Thanks for yours :)

**Comment by johannesjo** [comment]
I merged the changes. Hopefully the tests run through now

**Comment by tushariscoolster** [comment]
Yeah...lets see

**Comment by johannesjo** [comment]
Oki it worked out. Thanks again! It will be included it in the next release.

**Pull request merged**
