### PR TITLE
Adding Support for Dot Notation in Form Name

### PR DESCRIPTION
**Pull request by barefootdeveloper**
Adding the ability to have a dot notation string in the form name (ex.
<form name="ctrl.form">).  This is useful for people using the
controller as syntax.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much for your PR! There are some issues with the code formatting I'm afraid (mainly intendations) . It would be really nice if you could fix those, so I can avoid another cleanup commit.

**Comment by barefootdeveloper** [comment]
Yeah I'm pretty sure Windows screwed that up.  I noticed it looks weird when you view it on github but when I view it in visual studio / notepad ++ it looks fine.

The massive block of changes in the cachetemplate portion was done by the build scripts :( 

About the only thing I could think to do is perform the change again on my Mac when I go home?

snip1

**Comment by johannesjo** [comment]
@barefootdeveloper not using windows for development anymore so I'm not sure how to fix this... :/  If it is not too much trouble, it would be nice if you could give it another go. I will merge the PR then, test the changes and update the bower package if everything works fine.

**Comment by barefootdeveloper** [comment]
See if 04e80bb312d5e6d06b439e89ffcdb398fe909078 looks better to you.

**Comment by johannesjo** [comment]
@barefootdeveloper Thank you very much! :) I'll test the changes and then report back.

**Comment by barefootdeveloper** [comment]
Excellent, it's amazing what a linux virtual machine will do :)

**Comment by johannesjo** [comment]
Your PR made me think. When you can use the object reference, than it might be possible to use $parse. Which worked fine. While doing that I found out that the reference of scope[forName] is actually the same as the form-controller, so I ended up setting
```
privateScope.form = formCtrl;
privateScope.field = ngModelCtrl;
```
which also works fine. So the scope-model-value equals the controllers, which I find really interesting :) I will have a look at ng-model sometime to get an understanding why this is actually the case.

**Comment by johannesjo** [comment]
I merged the changes and made the update to the bower package. May I ask how you found this bug? Why did you have a form-name in dot-notation?

**Comment by barefootdeveloper** [comment]
Hey I'm all for simplicity and this change is way simpler.

When you're using controller as syntax with angular if you want access to the form you have to give the form a name of "ctrl.formname".

You can read about it here: http://www.technofattie.com/2014/07/01/using-angular-forms-with-controller-as-syntax.html

**Comment by johannesjo** [comment]
Interesting. Thanks for sharing! Wouldn't work with ng-route or the ui-router, at least not out of the box. But imho its much more expressive to use this instead of $scope. Makes all the inheritance stuff a little clearer. Haven't tried it yet, because I somewhere read there might be some unexpected issues, but that's a long time ago. Might give it another go.

**Comment by barefootdeveloper** [comment]
It definitely causes some pain now and then but in the end I think it produces a cleaner output.

Our project does actually use ui-router out of the box.

**Comment by micha1** [comment]
thanks for make it possible to use it  with controller as syntax . had some error till i read the note to the last commit so i updated and now it works

**Pull request merged**
